// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBx2TlwmPqOOGyqPH1RrIQ0xYOGRnbhyWo',
    appId: '1:1042272166078:web:cd16614d54a6c60e5bbeef',
    messagingSenderId: '1042272166078',
    projectId: 'rideshare-1ad1a',
    authDomain: 'rideshare-1ad1a.firebaseapp.com',
    storageBucket: 'rideshare-1ad1a.appspot.com',
    measurementId: 'G-EZRCN17YHF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFLxWUBYByjs6D-Ubmo6WvrcueZaUIG7c',
    appId: '1:1042272166078:android:0a0b161bff3c7dd35bbeef',
    messagingSenderId: '1042272166078',
    projectId: 'rideshare-1ad1a',
    storageBucket: 'rideshare-1ad1a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8712eRrj55xuKsMtygYn5unYo44PIm1E',
    appId: '1:1042272166078:ios:e7e0cd66ec19deab5bbeef',
    messagingSenderId: '1042272166078',
    projectId: 'rideshare-1ad1a',
    storageBucket: 'rideshare-1ad1a.appspot.com',
    iosBundleId: 'com.example.usersApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8712eRrj55xuKsMtygYn5unYo44PIm1E',
    appId: '1:1042272166078:ios:83a63073d7f206b55bbeef',
    messagingSenderId: '1042272166078',
    projectId: 'rideshare-1ad1a',
    storageBucket: 'rideshare-1ad1a.appspot.com',
    iosBundleId: 'com.example.usersApp.RunnerTests',
  );
}
